# Generated by Django 4.2.6 on 2024-07-03 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('template', '0004_remove_template_semesters'),
        ('semester', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=100)),
                ('semesters', models.ManyToManyField(to='semester.semester')),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='template.template')),
            ],
        ),
    ]
