# Generated by Django 4.2.6 on 2025-01-31 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0019_course_link'),
        ('plan', '0003_alter_plan_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='course_cart',
            field=models.ManyToManyField(blank=True, to='classes.course'),
        ),
    ]
