# Generated by Django 4.2.6 on 2025-02-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_plan_course_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='requirement_filled',
            field=models.BooleanField(default=False),
        ),
    ]
