# Generated by Django 4.2.6 on 2025-03-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_plan_requirement_filled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='course_cart',
        ),
        migrations.AddField(
            model_name='plan',
            name='course_cart',
            field=models.JSONField(default=list),
        ),
    ]
