# Generated by Django 4.2.6 on 2024-11-05 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('major', '0002_major_abbreviation_major_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=-1)),
                ('name', models.CharField(default='', max_length=100)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_type', to='major.major')),
            ],
        ),
    ]
