# Generated by Django 4.2.6 on 2024-10-31 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(default='', max_length=50)),
                ('requirement_type', models.CharField(default='credit', max_length=20)),
                ('requirement_size', models.IntegerField(default=1)),
            ],
        ),
    ]
