# Generated by Django 4.2.6 on 2024-11-05 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0002_major_abbreviation_major_name'),
        ('requirement', '0002_requirement_attribute_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='attribute_max',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='requirement',
            name='attribute_min',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='requirement',
            name='major',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='major.major'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='attribute_value',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='requirement_type',
            field=models.CharField(choices=[('==', 'Exactly'), ('>=', 'At least'), ('<=', 'At most'), ('>', 'More than'), ('<', 'Less than')], default='==', max_length=2),
        ),
    ]
