# Generated by Django 4.2.6 on 2024-11-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_type', '0001_initial'),
        ('requirement', '0004_remove_requirement_attribute_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='credit_type',
            field=models.ManyToManyField(to='credit_type.credittype'),
        ),
    ]
