# Generated by Django 4.2.6 on 2024-11-08 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit_type', '0001_initial'),
        ('requirement', '0005_requirement_credit_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='credit_type',
        ),
        migrations.AddField(
            model_name='requirement',
            name='credit_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='credit_type.credittype'),
        ),
    ]
