# Generated by Django 4.2.6 on 2024-11-09 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement', '0006_remove_requirement_credit_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='attribute',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='attribute_choice',
            field=models.CharField(blank=True, choices=[('==', 'Exactly'), ('>=', 'At least'), ('<=', 'At most'), ('>', 'More than'), ('<', 'Less than')], default='', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='attribute_value',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
