# Generated by Django 4.2.6 on 2024-11-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement', '0007_alter_requirement_attribute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='include',
            field=models.BooleanField(default=True),
        ),
    ]
