# Generated by Django 4.2.6 on 2024-10-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='abbreviation',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='major',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
