# Generated by Django 4.2.6 on 2024-03-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='elective_field',
            field=models.IntegerField(default=-1),
        ),
    ]
