# Generated by Django 4.2.6 on 2024-03-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_class_elective_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='title',
            field=models.CharField(default='', max_length=150),
        ),
    ]
