# Generated by Django 4.2.6 on 2024-03-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_class_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='abbreviation',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='class',
            name='coreq',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='class',
            name='prereq',
            field=models.CharField(max_length=10),
        ),
    ]
