# Generated by Django 4.2.6 on 2024-03-25 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_remove_course_prereq_course_prereqs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='prereqs',
            new_name='prereq',
        ),
    ]
