# Generated by Django 4.2.6 on 2024-03-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_rename_prereqs_course_prereq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='prereq',
            new_name='prereqs',
        ),
        migrations.RemoveField(
            model_name='course',
            name='coreq',
        ),
        migrations.AddField(
            model_name='course',
            name='coreqs',
            field=models.ManyToManyField(blank=True, related_name='corequisite_for', to='classes.course'),
        ),
    ]
