# Generated by Django 4.2.6 on 2024-07-11 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elective_field', '0001_initial'),
        ('classes', '0009_remove_course_elective_field_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='elective_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='elective_field.electivefield'),
        ),
    ]
