# Generated by Django 4.2.6 on 2024-07-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_alter_course_elective_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='class_number',
            field=models.CharField(default='XXXX', max_length=10),
        ),
    ]
