# Generated by Django 4.2.6 on 2024-07-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0011_course_class_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='term',
        ),
        migrations.AddField(
            model_name='course',
            name='season',
            field=models.CharField(choices=[('FALL', 'Fall'), ('SPRING', 'Spring'), ('SUMMER', 'Summer'), ('WINTER', 'Winter')], default='FALL', max_length=20),
        ),
    ]
