# Generated by Django 4.2.6 on 2024-07-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0001_initial'),
        ('classes', '0013_season_remove_course_season_course_seasons'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Season',
        ),
        migrations.AlterField(
            model_name='course',
            name='seasons',
            field=models.ManyToManyField(to='season.season'),
        ),
    ]
