# Generated by Django 4.2.6 on 2024-11-05 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit_type', '0001_initial'),
        ('classes', '0015_alter_course_class_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credit_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='credit_type.credittype'),
        ),
    ]
