# Generated by Django 4.2.6 on 2024-11-05 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0002_major_abbreviation_major_name'),
        ('classes', '0016_course_credit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='major',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='major.major'),
        ),
    ]
