# Generated by Django 4.2.6 on 2025-01-27 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0017_alter_course_major'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='abbreviation',
        ),
    ]
