# Generated by Django 4.2.6 on 2025-01-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0018_remove_course_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='link',
            field=models.TextField(default='https://cs.vt.edu/Graduate/Courses.html'),
        ),
    ]
