# Generated by Django 4.2.6 on 2025-03-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0019_course_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_id_list',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='course',
            name='class_number',
            field=models.IntegerField(default=4000),
        ),
    ]
