# Generated by Django 4.2.6 on 2025-03-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0020_course_course_id_list_alter_course_class_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='prereqs',
        ),
        migrations.AddField(
            model_name='course',
            name='prereq_groups',
            field=models.JSONField(default=list),
        ),
    ]
