# Generated by Django 4.2.6 on 2025-03-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0021_remove_course_prereqs_course_prereq_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='coreqs',
        ),
        migrations.AddField(
            model_name='course',
            name='coreq_groups',
            field=models.JSONField(default=list),
        ),
    ]
