# Generated by Django 4.2.6 on 2024-07-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('semester', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_credits', models.IntegerField(default=120)),
                ('requirements', models.JSONField(default=list)),
                ('major', models.TextField(default='')),
                ('semesters', models.ManyToManyField(to='semester.semester')),
            ],
        ),
    ]
