# Generated by Django 4.2.6 on 2024-07-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elective_field', '0001_initial'),
        ('template', '0002_template_elective_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='elective_fields',
            field=models.ManyToManyField(to='elective_field.electivefield'),
        ),
        migrations.AlterField(
            model_name='template',
            name='major',
            field=models.CharField(default='', max_length=100),
        ),
    ]
