# Generated by Django 4.2.6 on 2024-07-02 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0003_alter_template_elective_fields_alter_template_major'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='semesters',
        ),
    ]
