# Generated by Django 4.2.6 on 2024-07-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0004_remove_template_semesters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='requirements',
        ),
        migrations.AddField(
            model_name='template',
            name='min_each_Elective',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='template',
            name='min_elective_fields',
            field=models.IntegerField(default=1),
        ),
    ]
