# Generated by Django 4.2.6 on 2024-11-05 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0002_major_abbreviation_major_name'),
        ('template', '0008_remove_template_requirement_attribute_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='level',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='template',
            name='major',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='major.major'),
        ),
    ]
