# Generated by Django 4.2.6 on 2024-11-07 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0009_template_level_alter_template_major'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='abbreviation',
        ),
    ]
