# Generated by Django 4.2.6 on 2024-11-21 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0010_remove_template_abbreviation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='elective_fields',
        ),
    ]
