# Generated by Django 4.2.6 on 2024-07-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0008_rename_prereq_course_prereqs_remove_course_coreq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031), (2032, 2032), (2033, 2033)], default=2024)),
                ('season', models.CharField(choices=[('FALL', 'Fall'), ('SPRING', 'Spring'), ('SUMMER', 'Summer'), ('WINTER', 'Winter')], default='FALL', max_length=20)),
                ('current_credit', models.IntegerField(default=0)),
                ('max_credits', models.IntegerField(default=40)),
                ('min_credits', models.IntegerField(default=0)),
                ('classes', models.ManyToManyField(to='classes.course')),
            ],
        ),
    ]
