# Generated by Django 4.2.6 on 2024-07-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0001_initial'),
        ('semester', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='season',
        ),
        migrations.AddField(
            model_name='semester',
            name='season',
            field=models.ManyToManyField(to='season.season'),
        ),
    ]
