# Generated by Django 4.2.6 on 2024-07-16 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semester', '0002_remove_semester_season_semester_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='season',
        ),
    ]
