# Generated by Django 4.2.6 on 2024-07-16 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0001_initial'),
        ('semester', '0003_remove_semester_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='season.season'),
        ),
    ]
