# Generated by Django 4.2.6 on 2025-01-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semester', '0004_semester_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='year',
            field=models.IntegerField(choices=[(2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031), (2032, 2032), (2033, 2033), (2034, 2034)], default=2025),
        ),
    ]
