# Generated by Django 4.2.6 on 2025-01-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0019_course_link'),
        ('semester', '0005_alter_semester_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='classes',
            field=models.ManyToManyField(blank=True, to='classes.course'),
        ),
    ]
