# Generated by Django 4.2.6 on 2025-02-04 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semester', '0007_semester_max_credit_each_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='max_credit_each_semester',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='min_credit_each_semester',
        ),
    ]
