# Generated by Django 4.2.6 on 2025-03-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semester', '0008_remove_semester_max_credit_each_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='classes',
        ),
        migrations.AddField(
            model_name='semester',
            name='classes',
            field=models.JSONField(default=list),
        ),
    ]
