# Generated by Django 4.2.6 on 2024-07-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='plans',
            field=models.ManyToManyField(to='plan.plan'),
        ),
    ]
